version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nodejs
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      runas: root
    - location: scripts/start_app
      runas: root
